### ISSUE TITLE
Version v0.2 crashes pre lollipop

### ISSUE THREAD

**Issue by 0lumide** [0lumide/IntroActivity#1]
The sample app crashes pre-lollipop with this error `invalid drawable tag vector` when inflating the image buttons. This is the stacktrace

``````
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miz.introactivity/com.miz.introactivity.demo.DemoActivity}: android.view.InflateException: Binary XML file line #38: Error inflating class com.miz.introactivity.NextDoneButton
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
     at android.app.ActivityThread.access$900(ActivityThread.java:170)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:146)
     at android.app.ActivityThread.main(ActivityThread.java:5635)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
     at dalvik.system.NativeStart.main(Native Method)
  Caused by: android.view.InflateException: Binary XML file line #38: Error inflating class com.miz.introactivity.NextDoneButton
     at android.view.LayoutInflater.createView(LayoutInflater.java:626)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:463)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
     at com.miz.introactivity.IntroActivity.onCreate(IntroActivity.java:45)
     at android.app.Activity.performCreate(Activity.java:5585)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
     at android.app.ActivityThread.access$900(ActivityThread.java:170) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:146) 
     at android.app.ActivityThread.main(ActivityThread.java:5635) 
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:515) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
     at dalvik.system.NativeStart.main(Native Method) 
  Caused by: java.lang.reflect.InvocationTargetException
     at java.lang.reflect.Constructor.constructNative(Native Method)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     at android.view.LayoutInflater.createView(LayoutInflater.java:600)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:769) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:463) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
     at com.miz.introactivity.IntroActivity.onCreate(IntroActivity.java:45) 
     at android.app.Activity.performCreate(Activity.java:5585) 
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400) 
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
     at android.app.ActivityThread.access$900(ActivityThread.java:170) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:146) 
     at android.app.ActivityThread.main(ActivityThread.java:5635) 
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:515) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
     at dalvik.system.NativeStart.main(Native Method) 
  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/next.xml from drawable resource ID #0x7f02005b
     at android.content.res.Resources.loadDrawable(Resources.java:3439)
     at android.content.res.Resources.getDrawable(Resources.java:1893)
     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
     at com.miz.introactivity.NextDoneButton.initialize(NextDoneButton.java:42)
     at com.miz.introactivity.NextDoneButton.<init>(NextDoneButton.java:33)
     at java.lang.reflect.Constructor.constructNative(Native Method) 
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
     at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:769) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:463) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
     at com.miz.introactivity.IntroActivity.onCreate(IntroActivity.java:45) 
     at android.app.Activity.performCreate(Activity.java:5585) 
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400) 
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
     at android.app.ActivityThread.access$900(ActivityThread.java:170) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:146) 
     at android.app.ActivityThread.main(ActivityThread.java:5635) 
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:515) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
     at dalvik.system.NativeStart.main(Native Method) 
  Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
     at android.content.res.Resources.loadDrawable(Resources.java:3435)
     at android.content.res.Resources.getDrawable(Resources.java:1893) 
     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346) 
     at com.miz.introactivity.NextDoneButton.initialize(NextDoneButton.java:42) 
     at com.miz.introactivity.NextDoneButton.<init>(NextDoneButton.java:33) 
     at java.lang.reflect.Constructor.constructNative(Native Method) 
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
     at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:769) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:463) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
     at com.miz.introactivity.IntroActivity.onCreate(IntroActivity.java:45) 
     at android.app.Activity.performCreate(Activity.java:5585) 
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400) 
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
     at android.app.ActivityThread.access$900(ActivityThread.java:170) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:146) 
     at android.app.ActivityThread.main(ActivityThread.java:5635) 
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:515) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
     at dalvik.system.NativeStart.main(Native Method) ```
``````

**Comment by 0lumide** [comment]
Use version v0.2.1. The issue has been fixed in that version
